import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';
import 'package:uuid/uuid.dart';
import '../../domain/models/drawing.dart';
import '../../domain/models/drawing_type.dart';
import '../controllers/drawings_controller.dart';
import '../../../projects/presentation/controllers/projects_controller.dart';
import '../../../../core/theme/color_palette.dart';
import '../../../../core/utils/drawing_generator.dart';

class DrawingImportModal extends ConsumerStatefulWidget {
  final String? preselectedProjectId;

  const DrawingImportModal({super.key, this.preselectedProjectId});

  @override
  ConsumerState<DrawingImportModal> createState() => _DrawingImportModalState();
}

class _DrawingImportModalState extends ConsumerState<DrawingImportModal> {
  final _formKey = GlobalKey<FormState>();
  String? _selectedProjectId;
  late TextEditingController _numberController;
  late TextEditingController _titleController;
  DrawingType _selectedType = DrawingType.pid;
  String _selectedRevision = 'Rev 0';
  String? _selectedFilePath;
  String? _selectedFileName;
  int _selectedFileSize = 0;
  bool _isGeneratingPdf = false;
  bool _useAutoGeneratedVector = true;

  @override
  void initState() {
    super.initState();
    _selectedProjectId = widget.preselectedProjectId;
    _numberController = TextEditingController(text: 'DWG-${DateTime.now().millisecondsSinceEpoch % 10000}');
    _titleController = TextEditingController(text: 'New Field Engineering Drawing Specification');
  }

  @override
  void dispose() {
    _numberController.dispose();
    _titleController.dispose();
    super.dispose();
  }

  Future<void> _pickPdfFromDevice() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf'],
        allowMultiple: false,
      );

      if (result != null && result.files.isNotEmpty) {
        final file = result.files.first;
        if (file.path != null) {
          setState(() {
            _selectedFilePath = file.path;
            _selectedFileName = file.name;
            _selectedFileSize = file.size;
            _useAutoGeneratedVector = false;

            // Auto-fill drawing number from filename if helpful
            if (_numberController.text.startsWith('DWG-')) {
              _numberController.text = file.name.replaceAll('.pdf', '').toUpperCase();
            }
          });
        }
      }
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Could not open file picker: $e')),
      );
    }
  }

  Future<void> _importDrawing() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedProjectId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select an active project package.')),
      );
      return;
    }

    setState(() => _isGeneratingPdf = true);

    try {
      final projectsState = ref.read(projectsListNotifierProvider);
      final project = projectsState.projects.firstWhere(
        (p) => p.id == _selectedProjectId,
        orElse: () => projectsState.projects.first,
      );

      Drawing drawing;

      if (_useAutoGeneratedVector || _selectedFilePath == null) {
        // Generate authentic vector engineering PDF
        final generatedFile = await DrawingGenerator.generateSampleEngineeringPdf(
          drawingNumber: _numberController.text.trim(),
          title: _titleController.text.trim(),
          projectName: project.name,
          clientName: project.client,
          drawingType: _selectedType,
          revision: _selectedRevision,
          pageCount: 2,
        );

        final fileSize = await generatedFile.length();

        drawing = Drawing(
          id: const Uuid().v4(),
          projectId: _selectedProjectId!,
          drawingNumber: _numberController.text.trim(),
          title: _titleController.text.trim(),
          drawingType: _selectedType,
          revision: _selectedRevision,
          filePath: generatedFile.path,
          thumbnailPath: null,
          pageCount: 2,
          fileSize: fileSize,
          downloaded: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        await ref.read(allDrawingsNotifierProvider.notifier).addDrawing(drawing);
      } else {
        // Import external PDF file from tablet storage
        await ref.read(allDrawingsNotifierProvider.notifier).importPdfDrawing(
              projectId: _selectedProjectId!,
              sourceFilePath: _selectedFilePath!,
              drawingNumber: _numberController.text.trim(),
              title: _titleController.text.trim(),
              drawingType: _selectedType,
              revision: _selectedRevision,
            );
      }

      // Reload project drawings list
      ref.read(projectDrawingsNotifierProvider(_selectedProjectId!).notifier).loadDrawings();

      if (mounted) {
        Navigator.of(context).pop(true);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: AppColors.online,
            content: Text('Drawing ${_numberController.text.trim()} imported to offline tablet storage.'),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to import drawing: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final projectsState = ref.watch(projectsListNotifierProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkSurface : AppColors.lightSurface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
      ),
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
        top: 24,
        left: 28,
        right: 28,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Row(
                    children: [
                      Icon(Icons.picture_as_pdf_rounded, color: AppColors.safetyOrange, size: 26),
                      SizedBox(width: 10),
                      Text(
                        'Import Engineering Drawing to Tablet',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
                      ),
                    ],
                  ),
                  IconButton(
                    icon: const Icon(Icons.close_rounded),
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Project Selector
              DropdownButtonFormField<String>(
                value: _selectedProjectId ?? (projectsState.projects.isNotEmpty ? projectsState.projects.first.id : null),
                decoration: const InputDecoration(
                  labelText: 'Target Project Package *',
                  prefixIcon: Icon(Icons.folder_special_rounded, size: 20),
                ),
                items: projectsState.projects.map((p) {
                  return DropdownMenuItem(
                    value: p.id,
                    child: Text('${p.projectNumber} - ${p.name}', overflow: TextOverflow.ellipsis),
                  );
                }).toList(),
                onChanged: (val) {
                  setState(() => _selectedProjectId = val);
                },
                validator: (v) => v == null ? 'Project selection is required' : null,
              ),
              const SizedBox(height: 16),

              // Drawing Number & Revision Row
              Row(
                children: [
                  Expanded(
                    flex: 3,
                    child: TextFormField(
                      controller: _numberController,
                      decoration: const InputDecoration(
                        labelText: 'Drawing / Tag Number *',
                        hintText: 'e.g. 084-PID-002 or ISO-501',
                      ),
                      validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
                    ),
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    flex: 2,
                    child: DropdownButtonFormField<String>(
                      value: _selectedRevision,
                      decoration: const InputDecoration(labelText: 'Revision'),
                      items: ['Rev 0', 'Rev 1', 'Rev 2', 'Rev 3', 'Rev A', 'Rev B', 'Rev C', 'IFC', 'As-Built']
                          .map((r) => DropdownMenuItem(value: r, child: Text(r)))
                          .toList(),
                      onChanged: (val) {
                        if (val != null) setState(() => _selectedRevision = val);
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Drawing Title
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Drawing Title / System Description *',
                  hintText: 'e.g. Flare Header Knockout Drum & Relief Lines',
                ),
                validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              // Discipline / Drawing Type Selector
              DropdownButtonFormField<DrawingType>(
                value: _selectedType,
                decoration: const InputDecoration(labelText: 'Engineering Discipline / Drawing Type'),
                items: DrawingType.values.map((t) {
                  return DropdownMenuItem(
                    value: t,
                    child: Row(
                      children: [
                        Icon(t.icon, color: t.color, size: 18),
                        const SizedBox(width: 10),
                        Text(t.displayName),
                      ],
                    ),
                  );
                }).toList(),
                onChanged: (val) {
                  if (val != null) setState(() => _selectedType = val);
                },
              ),
              const SizedBox(height: 20),

              // File Source Selector Box
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: isDark ? AppColors.darkSurfaceVariant : AppColors.lightSurfaceVariant,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: AppColors.darkBorder.withOpacity(0.5)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'PDF Document Source',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                    ),
                    const SizedBox(height: 10),
                    RadioListTile<bool>(
                      value: true,
                      groupValue: _useAutoGeneratedVector,
                      title: const Text('Generate Certified Vector P&ID / Drawing PDF (Offline Engine)'),
                      subtitle: const Text('Generates complete A3 vector engineering drawing with title block, bill of materials and stamps.'),
                      onChanged: (v) => setState(() => _useAutoGeneratedVector = true),
                    ),
                    RadioListTile<bool>(
                      value: false,
                      groupValue: _useAutoGeneratedVector,
                      title: const Text('Import Local PDF File from Tablet / SD Card Storage'),
                      subtitle: Text(_selectedFileName != null
                          ? 'Selected file: $_selectedFileName (${(_selectedFileSize / 1024).toStringAsFixed(1)} KB)'
                          : 'Select an existing PDF from tablet files.'),
                      onChanged: (v) {
                        setState(() => _useAutoGeneratedVector = false);
                        if (_selectedFilePath == null) _pickPdfFromDevice();
                      },
                    ),
                    if (!_useAutoGeneratedVector) ...[
                      const SizedBox(height: 8),
                      Padding(
                        padding: const EdgeInsets.only(left: 24.0),
                        child: OutlinedButton.icon(
                          icon: const Icon(Icons.folder_open_rounded, size: 18),
                          label: Text(_selectedFileName == null ? 'Browse Device Files (.pdf)' : 'Choose Another PDF'),
                          onPressed: _pickPdfFromDevice,
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Action Buttons
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: _isGeneratingPdf ? null : () => Navigator.of(context).pop(),
                    child: const Text('Cancel'),
                  ),
                  const SizedBox(width: 14),
                  ElevatedButton.icon(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.safetyOrange,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
                    ),
                    icon: _isGeneratingPdf
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                          )
                        : const Icon(Icons.download_done_rounded, size: 20),
                    label: Text(_isGeneratingPdf ? 'Processing...' : 'Save to Offline Storage'),
                    onPressed: _isGeneratingPdf ? null : _importDrawing,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
