import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:file_picker/file_picker.dart';
import 'package:uuid/uuid.dart';
import '../../domain/models/drawing.dart';
import '../../domain/models/drawing_type.dart';
import '../controllers/drawings_controller.dart';
import '../../../projects/presentation/controllers/projects_controller.dart';
import '../../../../core/theme/color_palette.dart';
import '../../../../core/utils/drawing_generator.dart';

class DrawingImportModal extends ConsumerStatefulWidget {
  final String? preselectedProjectId;

  const DrawingImportModal({super.key, this.preselectedProjectId});

  @override
  ConsumerState<DrawingImportModal> createState() => _DrawingImportModalState();
}

class _DrawingImportModalState extends ConsumerState<DrawingImportModal> {
  final _formKey = GlobalKey<FormState>();
  String? _selectedProjectId;
  late TextEditingController _numberController;
  late TextEditingController _titleController;
  DrawingType _selectedType = DrawingType.pid;
  String _selectedRevision = 'Rev 0';
  String? _selectedFilePath;
  String? _selectedFileName;
  int _selectedFileSize = 0;
  bool _isGeneratingPdf = false;
  bool _useAutoGeneratedVector = true;
  bool _isImageFile = false;

  @override
  void initState() {
    super.initState();
    _selectedProjectId = widget.preselectedProjectId;
    _numberController = TextEditingController(text: 'DWG-${DateTime.now().millisecondsSinceEpoch % 10000}');
    _titleController = TextEditingController(text: 'New Field Engineering Blueprint / Drawing');
  }

  @override
  void dispose() {
    _numberController.dispose();
    _titleController.dispose();
    super.dispose();
  }

  Future<void> _pickDocumentFromDevice() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf', 'png', 'jpg', 'jpeg', 'webp', 'bmp', 'tif', 'tiff'],
        allowMultiple: false,
        withData: true,
      );

      if (result != null && result.files.isNotEmpty) {
        final file = result.files.first;
        final extension = (file.extension ?? '').toLowerCase();
        final isImg = ['png', 'jpg', 'jpeg', 'webp', 'bmp', 'tif', 'tiff'].contains(extension);

        String computedPath;
        if (kIsWeb && file.bytes != null) {
          final mime = isImg ? (extension == 'jpg' ? 'image/jpeg' : 'image/$extension') : 'application/pdf';
          computedPath = 'data:$mime;base64,${base64Encode(file.bytes!)}';
        } else {
          computedPath = file.path ?? file.name;
        }

        setState(() {
          _selectedFilePath = computedPath;
          _selectedFileName = file.name;
          _selectedFileSize = file.size;
          _useAutoGeneratedVector = false;
          _isImageFile = isImg;

          // Auto-fill drawing number from filename if helpful
          final cleanName = file.name.replaceAll(RegExp(r'\.[a-zA-Z0-9]+$'), '').toUpperCase();
          if (_numberController.text.startsWith('DWG-')) {
            _numberController.text = cleanName;
          }
          if (_titleController.text.startsWith('New Field Engineering')) {
            _titleController.text = cleanName.replaceAll('_', ' ').replaceAll('-', ' ');
          }
        });
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Could not open file picker: $e')),
      );
    }
  }

  Future<void> _importDrawing() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedProjectId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select an active project package.')),
      );
      return;
    }

    setState(() => _isGeneratingPdf = true);

    try {
      final projectsState = ref.read(projectsListNotifierProvider);
      final project = projectsState.projects.firstWhere(
        (p) => p.id == _selectedProjectId,
        orElse: () => projectsState.projects.first,
      );

      Drawing drawing;

      if (_useAutoGeneratedVector || _selectedFilePath == null) {
        // Generate authentic vector engineering PDF
        final generatedFile = await DrawingGenerator.generateSampleEngineeringPdf(
          drawingNumber: _numberController.text.trim(),
          title: _titleController.text.trim(),
          projectName: project.name,
          clientName: project.client,
          drawingType: _selectedType,
          revision: _selectedRevision,
          pageCount: 2,
        );

        final fileSize = await generatedFile.length();

        drawing = Drawing(
          id: const Uuid().v4(),
          projectId: _selectedProjectId!,
          drawingNumber: _numberController.text.trim(),
          title: _titleController.text.trim(),
          drawingType: _selectedType,
          revision: _selectedRevision,
          filePath: generatedFile.path,
          thumbnailPath: null,
          pageCount: 2,
          fileSize: fileSize,
          downloaded: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        await ref.read(allDrawingsNotifierProvider.notifier).addDrawing(drawing);
      } else {
        // Import local PDF or Image document
        final newDrawing = Drawing(
          id: const Uuid().v4(),
          projectId: _selectedProjectId!,
          drawingNumber: _numberController.text.trim(),
          title: _titleController.text.trim(),
          drawingType: _selectedType,
          revision: _selectedRevision,
          filePath: _selectedFilePath!,
          thumbnailPath: null,
          pageCount: 1,
          fileSize: _selectedFileSize > 0 ? _selectedFileSize : 102400,
          downloaded: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        await ref.read(allDrawingsNotifierProvider.notifier).addDrawing(newDrawing);
      }

      // Reload project drawings list
      ref.read(projectDrawingsNotifierProvider(_selectedProjectId!).notifier).loadDrawings();

      if (mounted) {
        Navigator.of(context).pop(true);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: AppColors.online,
            content: Text('Document ${_numberController.text.trim()} imported to offline tablet storage.'),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to import document: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final projectsState = ref.watch(projectsListNotifierProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkSurface : AppColors.lightSurface,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
      ),
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
        top: 24,
        left: 28,
        right: 28,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Header
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Row(
                    children: [
                      Icon(Icons.add_photo_alternate_rounded, color: AppColors.safetyOrange, size: 26),
                      SizedBox(width: 10),
                      Text(
                        'Upload Blueprint / Document (PDF & Image)',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 17),
                      ),
                    ],
                  ),
                  IconButton(
                    icon: const Icon(Icons.close_rounded),
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Project Selector
              DropdownButtonFormField<String>(
                value: _selectedProjectId ?? (projectsState.projects.isNotEmpty ? projectsState.projects.first.id : null),
                decoration: const InputDecoration(
                  labelText: 'Target Project Package *',
                  prefixIcon: Icon(Icons.folder_special_rounded, size: 20),
                ),
                items: projectsState.projects.map((p) {
                  return DropdownMenuItem(
                    value: p.id,
                    child: Text('${p.projectNumber} - ${p.name}', overflow: TextOverflow.ellipsis),
                  );
                }).toList(),
                onChanged: (val) {
                  setState(() => _selectedProjectId = val);
                },
                validator: (v) => v == null ? 'Project selection is required' : null,
              ),
              const SizedBox(height: 16),

              // Drawing Number & Revision Row
              Row(
                children: [
                  Expanded(
                    flex: 3,
                    child: TextFormField(
                      controller: _numberController,
                      decoration: const InputDecoration(
                        labelText: 'Drawing / Tag Number *',
                        hintText: 'e.g. 084-PID-002 or DWG-SITE-01',
                      ),
                      validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
                    ),
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    flex: 2,
                    child: DropdownButtonFormField<String>(
                      value: _selectedRevision,
                      decoration: const InputDecoration(labelText: 'Revision'),
                      items: ['Rev 0', 'Rev 1', 'Rev 2', 'Rev 3', 'Rev A', 'Rev B', 'Rev C', 'IFC', 'As-Built']
                          .map((r) => DropdownMenuItem(value: r, child: Text(r)))
                          .toList(),
                      onChanged: (val) {
                        if (val != null) setState(() => _selectedRevision = val);
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Drawing Title
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Drawing Title / System Description *',
                  hintText: 'e.g. Flare Header Knockout Drum & Relief Lines',
                ),
                validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              // Discipline / Drawing Type Selector
              DropdownButtonFormField<DrawingType>(
                value: _selectedType,
                decoration: const InputDecoration(labelText: 'Engineering Discipline / Drawing Type'),
                items: DrawingType.values.map((t) {
                  return DropdownMenuItem(
                    value: t,
                    child: Row(
                      children: [
                        Icon(t.icon, color: t.color, size: 18),
                        const SizedBox(width: 10),
                        Text(t.displayName),
                      ],
                    ),
                  );
                }).toList(),
                onChanged: (val) {
                  if (val != null) setState(() => _selectedType = val);
                },
              ),
              const SizedBox(height: 20),

              // File Source Selector Box (PDF or Image)
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: isDark ? AppColors.darkSurfaceVariant : AppColors.lightSurfaceVariant,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: AppColors.darkBorder.withOpacity(0.5)),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Document / Blueprint Source (PDF or Image)',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                    ),
                    const SizedBox(height: 10),
                    RadioListTile<bool>(
                      value: true,
                      groupValue: _useAutoGeneratedVector,
                      title: const Text('Generate Certified Vector P&ID / Drawing PDF (Offline Engine)'),
                      subtitle: const Text('Generates complete A3 vector engineering drawing with title block, bill of materials and stamps.'),
                      onChanged: (v) => setState(() => _useAutoGeneratedVector = true),
                    ),
                    RadioListTile<bool>(
                      value: false,
                      groupValue: _useAutoGeneratedVector,
                      title: const Text('Import Local PDF or Image Blueprint (.pdf, .png, .jpg, .webp)'),
                      subtitle: Text(_selectedFileName != null
                          ? 'Selected ${_isImageFile ? "IMAGE" : "PDF"}: $_selectedFileName (${(_selectedFileSize / 1024).toStringAsFixed(1)} KB)'
                          : 'Select any PDF blueprint or high-resolution photo/drawing image from tablet storage.'),
                      onChanged: (v) {
                        setState(() => _useAutoGeneratedVector = false);
                        if (_selectedFilePath == null) _pickDocumentFromDevice();
                      },
                    ),
                    if (!_useAutoGeneratedVector) ...[
                      const SizedBox(height: 8),
                      Padding(
                        padding: const EdgeInsets.only(left: 24.0),
                        child: Wrap(
                          spacing: 12,
                          children: [
                            OutlinedButton.icon(
                              icon: const Icon(Icons.upload_file_rounded, size: 18),
                              label: Text(_selectedFileName == null
                                  ? 'Browse Files (PDF or Image)'
                                  : 'Choose Another File'),
                              onPressed: _pickDocumentFromDevice,
                            ),
                            if (_selectedFileName != null)
                              Chip(
                                avatar: Icon(
                                  _isImageFile ? Icons.image_rounded : Icons.picture_as_pdf_rounded,
                                  size: 16,
                                  color: _isImageFile ? Colors.teal : Colors.red,
                                ),
                                label: Text(
                                  _isImageFile ? 'IMAGE BLUEPRINT' : 'PDF DOCUMENT',
                                  style: TextStyle(
                                    fontSize: 10,
                                    fontWeight: FontWeight.bold,
                                    color: _isImageFile ? Colors.teal : Colors.red,
                                  ),
                                ),
                                backgroundColor: (_isImageFile ? Colors.teal : Colors.red).withOpacity(0.12),
                              ),
                          ],
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Action Buttons
              Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  TextButton(
                    onPressed: _isGeneratingPdf ? null : () => Navigator.of(context).pop(),
                    child: const Text('Cancel'),
                  ),
                  const SizedBox(width: 14),
                  ElevatedButton.icon(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.safetyOrange,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
                    ),
                    icon: _isGeneratingPdf
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                          )
                        : const Icon(Icons.download_done_rounded, size: 20),
                    label: Text(_isGeneratingPdf ? 'Processing...' : 'Save to Offline Storage'),
                    onPressed: _isGeneratingPdf ? null : _importDrawing,
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
